version: '3.9'

services:

  portfolio:
    build: .
    command: npm run dev
    container_name: portfolio
    env_file:
      - .env
    volumes:
      - .:/home/portfolio
    ports:
      - 3000:3000
