networks:
  webnet:
    external: true

services:
  portifolio:
    build: .
    container_name: portifolio
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet